/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var localizedStrings = {
    "Account Name (optional)": "Account Name (optional)",
    "Account: ": "Account: ",
    "Debug": "Debug",
    "Done": "Done",
    "Error!": "Error!",
    "Get Key": "Get Key",
    "GET YOUR KEY": "Enter your personal Ping.FM Application Key below; click the button at right if you don't know your Application Key.",
    "Post": "Post",
    "Validate": "Validate",
    "Version": "Version"
};
