--- !ditz.rubyforge.org,2008-03-06/project 
name: pb
version: "0.4"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: pb
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.5"
  status: :released
  release_time: 2008-08-20 03:19:27.932781 Z
  log_events: 
  - - 2008-08-09 17:46:17.391909 Z
    - Robert Sanders <robert@esquimaux.org>
    - created
    - persistent local storage? and multi-svc posting
  - - 2008-08-20 03:19:27.932792 Z
    - Robert Sanders <robert@esquimaux.org>
    - released
    - added partial service posting
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.6"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2008-08-09 18:19:08.494595 Z
    - Robert Sanders <robert@esquimaux.org>
    - created
    - include better blog editor
- !ditz.rubyforge.org,2008-03-06/release 
  name: 0.4.2
  status: :released
  release_time: 2008-08-20 03:19:49.312105 Z
  log_events: 
  - - 2008-08-09 18:19:59.789819 Z
    - Robert Sanders <robert@esquimaux.org>
    - created
    - |-
      better UI for service info
      indication for debug status
  - - 2008-08-20 03:19:49.312120 Z
    - Robert Sanders <robert@esquimaux.org>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.7"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2008-08-20 03:20:00.890393 Z
    - Robert Sanders <robert@esquimaux.org>
    - created
    - ""
